# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myprofileO.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class MyProfileO_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 302)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 601, 269))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.emailLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.emailLabel.setObjectName("emailLabel")
        self.gridLayout.addWidget(self.emailLabel, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 3, 1, 1)
        self.cnpjcheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.cnpjcheckBox.setObjectName("cnpjcheckBox")
        self.gridLayout.addWidget(self.cnpjcheckBox, 5, 5, 1, 1)
        self.segmLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.segmLabel.setObjectName("segmLabel")
        self.gridLayout.addWidget(self.segmLabel, 3, 0, 1, 1)
        self.citycheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.citycheckBox.setObjectName("citycheckBox")
        self.gridLayout.addWidget(self.citycheckBox, 4, 5, 1, 1)
        self.cnpjLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cnpjLabel.setObjectName("cnpjLabel")
        self.gridLayout.addWidget(self.cnpjLabel, 5, 0, 1, 1)
        self.segmcheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.segmcheckBox.setObjectName("segmcheckBox")
        self.gridLayout.addWidget(self.segmcheckBox, 3, 5, 1, 1)
        self.segmLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.segmLineEdit.setObjectName("segmLineEdit")
        self.gridLayout.addWidget(self.segmLineEdit, 3, 4, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.nameLineEdit.setText("")
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout.addWidget(self.nameLineEdit, 1, 2, 1, 3)
        self.cnpjLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cnpjLineEdit.setObjectName("cnpjLineEdit")
        self.gridLayout.addWidget(self.cnpjLineEdit, 5, 2, 1, 3)
        self.namecheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.namecheckBox.setObjectName("namecheckBox")
        self.gridLayout.addWidget(self.namecheckBox, 1, 5, 1, 1)
        self.cityLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cityLineEdit.setObjectName("cityLineEdit")
        self.gridLayout.addWidget(self.cityLineEdit, 4, 2, 1, 3)
        self.nameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 1, 0, 1, 1)
        self.emailcheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.emailcheckBox.setObjectName("emailcheckBox")
        self.gridLayout.addWidget(self.emailcheckBox, 2, 5, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(4, "")
        self.gridLayout.addWidget(self.comboBox, 3, 2, 1, 1)
        self.cityLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cityLabel.setObjectName("cityLabel")
        self.gridLayout.addWidget(self.cityLabel, 4, 0, 1, 1)
        self.emailLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.gridLayout.addWidget(self.emailLineEdit, 2, 2, 1, 3)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 6)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 0, 1, 6)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 621, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.emailLabel.setText(_translate("MainWindow", "E-mail:"))
        self.label_3.setText(_translate("MainWindow", "Outro:"))
        self.cnpjcheckBox.setText(_translate("MainWindow", "Privado"))
        self.segmLabel.setText(_translate("MainWindow", "Segmento"))
        self.citycheckBox.setText(_translate("MainWindow", "Privado"))
        self.cnpjLabel.setText(_translate("MainWindow", "CNPJ"))
        self.segmcheckBox.setText(_translate("MainWindow", "Privado"))
        self.namecheckBox.setText(_translate("MainWindow", "Privado"))
        self.nameLabel.setText(_translate("MainWindow", "Nome:"))
        self.emailcheckBox.setText(_translate("MainWindow", "Privado"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Alimentação"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Vestuário"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Indústria"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Saúde"))
        self.comboBox.setItemText(4, _translate("MainWindow", ""))
        self.cityLabel.setText(_translate("MainWindow", "Cidade:"))
        self.label.setText(_translate("MainWindow", "XXXX"))
        self.pushButton.setText(_translate("MainWindow", "Atualizar"))
        self.label_2.setText(_translate("MainWindow", ""))

