# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myprofileP.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class MyProfileP_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 321)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 591, 269))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.citycheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.citycheckBox.setObjectName("citycheckBox")
        self.gridLayout.addWidget(self.citycheckBox, 4, 2, 1, 1)
        self.emailLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.gridLayout.addWidget(self.emailLineEdit, 3, 1, 1, 1)
        self.borncheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.borncheckBox.setObjectName("borncheckBox")
        self.gridLayout.addWidget(self.borncheckBox, 2, 2, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 1, 0, 1, 1)
        self.cpfLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cpfLineEdit.setObjectName("cpfLineEdit")
        self.gridLayout.addWidget(self.cpfLineEdit, 5, 1, 1, 1)
        self.cityLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cityLineEdit.setObjectName("cityLineEdit")
        self.gridLayout.addWidget(self.cityLineEdit, 4, 1, 1, 1)
        self.cpfLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cpfLabel.setObjectName("cpfLabel")
        self.gridLayout.addWidget(self.cpfLabel, 5, 0, 1, 1)
        self.emailLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.emailLabel.setObjectName("emailLabel")
        self.gridLayout.addWidget(self.emailLabel, 3, 0, 1, 1)
        self.bornLineEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.bornLineEdit.setCalendarPopup(True)
        self.bornLineEdit.setObjectName("bornLineEdit")
        maxDate = QtCore.QDate.currentDate().addYears(-15).addDays(1) #add
        self.bornLineEdit.setMaximumDate(maxDate) #add
        self.gridLayout.addWidget(self.bornLineEdit, 2, 1, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.nameLineEdit.setText("")
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout.addWidget(self.nameLineEdit, 1, 1, 1, 1)
        self.emailcheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.emailcheckBox.setObjectName("emailcheckBox")
        self.gridLayout.addWidget(self.emailcheckBox, 3, 2, 1, 1)
        self.cpfcheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.cpfcheckBox.setObjectName("cpfcheckBox")
        self.gridLayout.addWidget(self.cpfcheckBox, 5, 2, 1, 1)
        self.namecheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.namecheckBox.setObjectName("namecheckBox")
        self.gridLayout.addWidget(self.namecheckBox, 1, 2, 1, 1)
        self.cityLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cityLabel.setObjectName("cityLabel")
        self.gridLayout.addWidget(self.cityLabel, 4, 0, 1, 1)
        self.bornLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.bornLabel.setObjectName("bornLabel")
        self.gridLayout.addWidget(self.bornLabel, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 624, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.citycheckBox.setText(_translate("MainWindow", "Privado"))
        self.borncheckBox.setText(_translate("MainWindow", "Privado"))
        self.nameLabel.setText(_translate("MainWindow", "Nome:"))
        self.cpfLabel.setText(_translate("MainWindow", "CPF:"))
        self.emailLabel.setText(_translate("MainWindow", "E-mail:"))
        self.bornLineEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.emailcheckBox.setText(_translate("MainWindow", "Privado"))
        self.cpfcheckBox.setText(_translate("MainWindow", "Privado"))
        self.namecheckBox.setText(_translate("MainWindow", "Privado"))
        self.cityLabel.setText(_translate("MainWindow", "Cidade:"))
        self.bornLabel.setText(_translate("MainWindow", "Data de nascimento:"))
        self.pushButton.setText(_translate("MainWindow", "Atualizar"))
        self.label.setText(_translate("MainWindow", "XXXX"))
        self.label_2.setText(_translate("MainWindow", ""))

