# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profileO.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ProfileO_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(441, 376)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 431, 319))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cityLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cityLabel_2.setObjectName("cityLabel_2")
        self.gridLayout.addWidget(self.cityLabel_2, 4, 0, 1, 1)
        self.connLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.connLabel_2.setObjectName("connLabel_2")
        self.gridLayout.addWidget(self.connLabel_2, 7, 0, 1, 1)
        self.ConnectpushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ConnectpushButton_2.setObjectName("ConnectpushButton_2")
        self.gridLayout.addWidget(self.ConnectpushButton_2, 10, 1, 1, 1)
        self.namelabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.namelabel.setText("")
        self.namelabel.setObjectName("namelabel")
        self.gridLayout.addWidget(self.namelabel, 1, 1, 1, 1)
        self.cnpjLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cnpjLabel_2.setObjectName("cnpjLabel_2")
        self.gridLayout.addWidget(self.cnpjLabel_2, 6, 0, 1, 1)
        self.cityLabel_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cityLabel_7.setObjectName("cityLabel_7")
        self.gridLayout.addWidget(self.cityLabel_7, 10, 0, 1, 1)
        self.DisconnectpushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.DisconnectpushButton_2.setObjectName("DisconnectpushButton_2")
        self.gridLayout.addWidget(self.DisconnectpushButton_2, 11, 1, 1, 1)
        self.cityLabel_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cityLabel_8.setObjectName("cityLabel_8")
        self.gridLayout.addWidget(self.cityLabel_8, 11, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.bornLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.bornLabel_2.setObjectName("bornLabel_2")
        self.gridLayout.addWidget(self.bornLabel_2, 2, 0, 1, 1)
        self.segmlabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.segmlabel.setText("")
        self.segmlabel.setObjectName("segmlabel")
        self.gridLayout.addWidget(self.segmlabel, 2, 1, 1, 1)
        self.emailLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.emailLabel_2.setObjectName("emailLabel_2")
        self.gridLayout.addWidget(self.emailLabel_2, 3, 0, 1, 1)
        self.emaillabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.emaillabel.setText("")
        self.emaillabel.setObjectName("emaillabel")
        self.gridLayout.addWidget(self.emaillabel, 3, 1, 1, 1)
        self.nameLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.gridLayout.addWidget(self.nameLabel_2, 1, 0, 1, 1)
        self.citylabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.citylabel.setText("")
        self.citylabel.setObjectName("citylabel")
        self.gridLayout.addWidget(self.citylabel, 4, 1, 1, 1)
        self.connlabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.connlabel.setText("")
        self.connlabel.setObjectName("connlabel")
        self.gridLayout.addWidget(self.connlabel, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        self.cnpjlabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cnpjlabel.setText("")
        self.cnpjlabel.setObjectName("cnpjlabel")
        self.gridLayout.addWidget(self.cnpjlabel, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 12, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 441, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cityLabel_2.setText(_translate("MainWindow", "Cidade:"))
        self.connLabel_2.setText(_translate("MainWindow", "Conexão:"))
        self.ConnectpushButton_2.setText(_translate("MainWindow", "OK"))
        self.cnpjLabel_2.setText(_translate("MainWindow", "CNPJ:"))
        self.cityLabel_7.setText(_translate("MainWindow", "Conectar"))
        self.DisconnectpushButton_2.setText(_translate("MainWindow", "OK"))
        self.cityLabel_8.setText(_translate("MainWindow", "Desconectar"))
        self.bornLabel_2.setText(_translate("MainWindow", "Segmento:"))
        self.emailLabel_2.setText(_translate("MainWindow", "E-mail:"))
        self.nameLabel_2.setText(_translate("MainWindow", "Nome:"))
        self.label_2.setText(_translate("MainWindow", "XXXX"))

