# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profileP.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ProfileP_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(458, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 430, 305))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bornLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.bornLabel.setObjectName("bornLabel")
        self.gridLayout.addWidget(self.bornLabel, 1, 0, 1, 1)
        self.cityLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cityLabel_2.setText("")
        self.cityLabel_2.setObjectName("cityLabel_2")
        self.gridLayout.addWidget(self.cityLabel_2, 3, 1, 1, 1)
        self.emailLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.emailLabel_2.setText("")
        self.emailLabel_2.setObjectName("emailLabel_2")
        self.gridLayout.addWidget(self.emailLabel_2, 2, 1, 1, 1)
        self.bornLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.bornLabel_2.setText("")
        self.bornLabel_2.setObjectName("bornLabel_2")
        self.gridLayout.addWidget(self.bornLabel_2, 1, 1, 1, 1)
        self.nameLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nameLabel_2.setText("")
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.gridLayout.addWidget(self.nameLabel_2, 0, 1, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.emailLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.emailLabel.setObjectName("emailLabel")
        self.gridLayout.addWidget(self.emailLabel, 2, 0, 1, 1)
        self.cpfLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cpfLabel_2.setText("")
        self.cpfLabel_2.setObjectName("cpfLabel_2")
        self.gridLayout.addWidget(self.cpfLabel_2, 4, 1, 1, 1)
        self.cityLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cityLabel.setObjectName("cityLabel")
        self.gridLayout.addWidget(self.cityLabel, 3, 0, 1, 1)
        self.cpfLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cpfLabel.setObjectName("cpfLabel")
        self.gridLayout.addWidget(self.cpfLabel, 4, 0, 1, 1)
        self.connLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.connLabel.setObjectName("connLabel")
        self.gridLayout.addWidget(self.connLabel, 5, 0, 1, 1)
        self.connLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.connLabel_2.setText("")
        self.connLabel_2.setObjectName("connLabel_2")
        self.gridLayout.addWidget(self.connLabel_2, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cityLabel_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cityLabel_3.setObjectName("cityLabel_3")
        self.horizontalLayout.addWidget(self.cityLabel_3)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.ConnectpushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ConnectpushButton.setObjectName("ConnectpushButton")
        self.horizontalLayout.addWidget(self.ConnectpushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cityLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cityLabel_4.setObjectName("cityLabel_4")
        self.horizontalLayout_2.addWidget(self.cityLabel_4)
        self.DisconnectpushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.DisconnectpushButton.setObjectName("DisconnectpushButton")
        self.horizontalLayout_2.addWidget(self.DisconnectpushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.disconnectedLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.disconnectedLabel.setText("")
        self.disconnectedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.disconnectedLabel.setObjectName("disconnectedLabel")
        self.verticalLayout.addWidget(self.disconnectedLabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 458, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "XXXX"))
        self.bornLabel.setText(_translate("MainWindow", "Data de nascimento:"))
        self.nameLabel.setText(_translate("MainWindow", "Nome:"))
        self.emailLabel.setText(_translate("MainWindow", "E-mail:"))
        self.cityLabel.setText(_translate("MainWindow", "Cidade:"))
        self.cpfLabel.setText(_translate("MainWindow", "CPF:"))
        self.connLabel.setText(_translate("MainWindow", "Conexão:"))
        self.cityLabel_3.setText(_translate("MainWindow", "Conectar"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Amigo"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Conhecido"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Família"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Cliente"))
        self.ConnectpushButton.setText(_translate("MainWindow", "OK"))
        self.cityLabel_4.setText(_translate("MainWindow", "Desconectar"))
        self.DisconnectpushButton.setText(_translate("MainWindow", "OK"))

