# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Search_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(378, 259)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 359, 198))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.OrgradioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.OrgradioButton.setObjectName("OrgradioButton")
        self.gridLayout.addWidget(self.OrgradioButton, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.PersoncomboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PersoncomboBox.setObjectName("PersoncomboBox")
        self.PersoncomboBox.addItem("")
        self.PersoncomboBox.addItem("")
        self.PersoncomboBox.addItem("")
        self.PersoncomboBox.addItem("")
        self.PersoncomboBox.addItem("")
        self.PersoncomboBox.addItem("")
        self.gridLayout.addWidget(self.PersoncomboBox, 1, 1, 1, 1)
        self.titleLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        font = QtGui.QFont()
        font.setFamily("Jamrul")
        font.setPointSize(14)
        self.titleLabel.setFont(font)
        self.gridLayout.addWidget(self.titleLabel, 0, 0, 1, 3)
        self.PersonradioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.PersonradioButton.setObjectName("PersonradioButton")
        self.PersonradioButton.setChecked(True)
        self.gridLayout.addWidget(self.PersonradioButton, 1, 2, 1, 1)
        self.OrgcomboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.OrgcomboBox.setObjectName("OrgcomboBox")
        self.OrgcomboBox.addItem("")
        self.OrgcomboBox.addItem("")
        self.OrgcomboBox.addItem("")
        self.OrgcomboBox.addItem("")
        self.OrgcomboBox.addItem("")
        self.OrgcomboBox.addItem("")
        self.gridLayout.addWidget(self.OrgcomboBox, 2, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 2)
        self.notFoundLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.notFoundLabel.setText("")
        self.notFoundLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.notFoundLabel.setObjectName("notFoundLabel")
        self.gridLayout.addWidget(self.notFoundLabel, 5, 0, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setAutoDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 378, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Busca:"))
        self.OrgradioButton.setText(_translate("MainWindow", "Or&ganização"))
        self.label.setText(_translate("MainWindow", "Buscar por "))
        self.label_2.setText(_translate("MainWindow", "Buscar por "))
        self.PersoncomboBox.setItemText(0, _translate("MainWindow", "Nome"))
        self.PersoncomboBox.setItemText(1, _translate("MainWindow", "Data de nascimento"))
        self.PersoncomboBox.setItemText(2, _translate("MainWindow", "E-mail"))
        self.PersoncomboBox.setItemText(3, _translate("MainWindow", "Cidade"))
        self.PersoncomboBox.setItemText(4, _translate("MainWindow", "CPF"))
        self.PersoncomboBox.setItemText(5, _translate("MainWindow", "Usuário"))
        self.titleLabel.setText(_translate("MainWindow", "Busca de usuários"))
        self.PersonradioButton.setText(_translate("MainWindow", "Pessoa"))
        self.OrgcomboBox.setItemText(0, _translate("MainWindow", "Nome"))
        self.OrgcomboBox.setItemText(1, _translate("MainWindow", "Segmento"))
        self.OrgcomboBox.setItemText(2, _translate("MainWindow", "E-mail"))
        self.OrgcomboBox.setItemText(3, _translate("MainWindow", "Cidade"))
        self.OrgcomboBox.setItemText(4, _translate("MainWindow", "CNPJ"))
        self.OrgcomboBox.setItemText(5, _translate("MainWindow", "Usuário"))
        self.pushButton.setText(_translate("MainWindow", "Buscar"))

