# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signupPersonal.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class SignUpPersonal_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 426))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Createlabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Createlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Createlabel.setObjectName("Createlabel")
        self.verticalLayout.addWidget(self.Createlabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.usrLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.usrLabel.setObjectName("usrLabel")
        self.gridLayout.addWidget(self.usrLabel, 6, 0, 1, 1)
        self.usrLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.usrLineEdit.setObjectName("usrLineEdit")
        self.gridLayout.addWidget(self.usrLineEdit, 6, 1, 1, 1)
        self.emailLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.emailLabel.setObjectName("emailLabel")
        self.gridLayout.addWidget(self.emailLabel, 2, 0, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout.addWidget(self.nameLineEdit, 0, 1, 1, 1)
        self.cpfLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cpfLabel.setObjectName("cpfLabel")
        self.gridLayout.addWidget(self.cpfLabel, 4, 0, 1, 1)
        self.emailLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.gridLayout.addWidget(self.emailLineEdit, 2, 1, 1, 1)
        self.passwrdLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.passwrdLineEdit.setObjectName("passwrdLineEdit")
        self.gridLayout.addWidget(self.passwrdLineEdit, 7, 1, 1, 1)
        self.passwrdLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.passwrdLabel.setObjectName("passwrdLabel")
        self.gridLayout.addWidget(self.passwrdLabel, 7, 0, 1, 1)
        self.cpfLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.cpfLineEdit.setObjectName("cpfLineEdit")
        self.gridLayout.addWidget(self.cpfLineEdit, 4, 1, 1, 1)
        self.cityLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.cityLineEdit.setObjectName("cityLineEdit")
        self.gridLayout.addWidget(self.cityLineEdit, 3, 1, 1, 1)
        self.bornLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.bornLabel.setObjectName("bornLabel")
        self.gridLayout.addWidget(self.bornLabel, 1, 0, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.cityLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cityLabel.setObjectName("cityLabel")
        self.gridLayout.addWidget(self.cityLabel, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.namecheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.namecheckBox.setObjectName("namecheckBox")
        self.gridLayout.addWidget(self.namecheckBox, 0, 2, 1, 1)
        self.borncheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.borncheckBox.setObjectName("borncheckBox")
        self.gridLayout.addWidget(self.borncheckBox, 1, 2, 1, 1)
        self.emailcheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.emailcheckBox.setObjectName("emailcheckBox")
        self.gridLayout.addWidget(self.emailcheckBox, 2, 2, 1, 1)
        self.citycheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.citycheckBox.setObjectName("citycheckBox")
        self.gridLayout.addWidget(self.citycheckBox, 3, 2, 1, 1)
        self.cpfcheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cpfcheckBox.setObjectName("cpfcheckBox")
        self.gridLayout.addWidget(self.cpfcheckBox, 4, 2, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        maxDate = QtCore.QDate.currentDate().addYears(-15).addDays(1)
        self.dateEdit.setDate(maxDate)
        self.dateEdit.setMaximumDate(maxDate)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDisplayFormat("dd/MM/yyyy")
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.CreatepushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.CreatepushButton.setObjectName("CreatepushButton")
        self.verticalLayout.addWidget(self.CreatepushButton)
        self.UrsErrorlabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.UrsErrorlabel.setText("")
        self.UrsErrorlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.UrsErrorlabel.setObjectName("UrsErrorlabel")
        self.verticalLayout.addWidget(self.UrsErrorlabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Createlabel.setText(_translate("MainWindow", "Crie sua conta pessoal"))
        self.usrLabel.setText(_translate("MainWindow", "Usuário: "))
        self.emailLabel.setText(_translate("MainWindow", "E-mail:"))
        self.cpfLabel.setText(_translate("MainWindow", "CPF (apenas dígitos): "))
        self.passwrdLabel.setText(_translate("MainWindow", "Senha: "))
        self.bornLabel.setText(_translate("MainWindow", "Data de nascimento:"))
        self.nameLabel.setText(_translate("MainWindow", "Nome:"))
        self.cityLabel.setText(_translate("MainWindow", "Cidade: "))
        self.namecheckBox.setText(_translate("MainWindow", "Privado"))
        self.borncheckBox.setText(_translate("MainWindow", "Privado"))
        self.emailcheckBox.setText(_translate("MainWindow", "Privado"))
        self.citycheckBox.setText(_translate("MainWindow", "Privado"))
        self.cpfcheckBox.setText(_translate("MainWindow", "Privado"))
        self.CreatepushButton.setText(_translate("MainWindow", "Criar conta"))

