# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signupOrg.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class SignUpOrg_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 532)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 466))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Createlabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Createlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Createlabel.setObjectName("Createlabel")
        self.verticalLayout.addWidget(self.Createlabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.segmLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.segmLineEdit.setObjectName("segmLineEdit")
        self.horizontalLayout.addWidget(self.segmLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 2, 1, 1)
        self.emailLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.emailLabel.setObjectName("emailLabel")
        self.gridLayout.addWidget(self.emailLabel, 2, 0, 1, 1)
        self.emailLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.gridLayout.addWidget(self.emailLineEdit, 2, 2, 1, 1)
        self.usrLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.usrLabel.setObjectName("usrLabel")
        self.gridLayout.addWidget(self.usrLabel, 9, 0, 1, 1)
        self.usrLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.usrLineEdit.setObjectName("usrLineEdit")
        self.gridLayout.addWidget(self.usrLineEdit, 9, 2, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout.addWidget(self.nameLineEdit, 0, 2, 1, 1)
        self.cnpjLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cnpjLabel.setObjectName("cnpjLabel")
        self.gridLayout.addWidget(self.cnpjLabel, 7, 0, 1, 1)
        self.passwrdLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.passwrdLineEdit.setObjectName("passwrdLineEdit")
        self.gridLayout.addWidget(self.passwrdLineEdit, 10, 2, 1, 1)
        self.passwrdLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.passwrdLabel.setObjectName("passwrdLabel")
        self.gridLayout.addWidget(self.passwrdLabel, 10, 0, 1, 1)
        self.cnpjLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.cnpjLineEdit.setObjectName("cnpjLineEdit")
        self.gridLayout.addWidget(self.cnpjLineEdit, 7, 2, 1, 1)
        self.cityLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.cityLineEdit.setObjectName("cityLineEdit")
        self.gridLayout.addWidget(self.cityLineEdit, 6, 2, 1, 1)
        self.segmLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.segmLabel.setObjectName("segmLabel")
        self.gridLayout.addWidget(self.segmLabel, 4, 0, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.cityLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cityLabel.setObjectName("cityLabel")
        self.gridLayout.addWidget(self.cityLabel, 6, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 1)
        self.namecheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.namecheckBox.setObjectName("namecheckBox")
        self.gridLayout.addWidget(self.namecheckBox, 0, 3, 1, 1)
        self.segmcheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.segmcheckBox.setObjectName("segmcheckBox")
        self.gridLayout.addWidget(self.segmcheckBox, 4, 3, 1, 1)
        self.citycheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.citycheckBox.setObjectName("citycheckBox")
        self.gridLayout.addWidget(self.citycheckBox, 6, 3, 1, 1)
        self.cnpjcheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cnpjcheckBox.setObjectName("cnpjcheckBox")
        self.gridLayout.addWidget(self.cnpjcheckBox, 7, 3, 1, 1)
        self.emailcheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.emailcheckBox.setObjectName("emailcheckBox")
        self.gridLayout.addWidget(self.emailcheckBox, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.CreatepushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.CreatepushButton.setObjectName("CreatepushButton")
        self.verticalLayout.addWidget(self.CreatepushButton)
        self.UrsErrorlabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.UrsErrorlabel.setText("")
        self.UrsErrorlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.UrsErrorlabel.setObjectName("UrsErrorlabel")
        self.verticalLayout.addWidget(self.UrsErrorlabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Createlabel.setText(_translate("MainWindow", "Crie uma conta para sua organização"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Alimentação"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Vestuário"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Indústria"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Saúde"))
        self.label.setText(_translate("MainWindow", "Outro:"))
        self.emailLabel.setText(_translate("MainWindow", "E-mail:"))
        self.usrLabel.setText(_translate("MainWindow", "Usuário:"))
        self.cnpjLabel.setText(_translate("MainWindow", "CNPJ (apenas dígitos):"))
        self.passwrdLabel.setText(_translate("MainWindow", "Senha:"))
        self.segmLabel.setText(_translate("MainWindow", "Segmento:"))
        self.nameLabel.setText(_translate("MainWindow", "Nome:"))
        self.cityLabel.setText(_translate("MainWindow", "Cidade:"))
        self.namecheckBox.setText(_translate("MainWindow", "Privado"))
        self.segmcheckBox.setText(_translate("MainWindow", "Privado"))
        self.citycheckBox.setText(_translate("MainWindow", "Privado"))
        self.cnpjcheckBox.setText(_translate("MainWindow", "Privado"))
        self.emailcheckBox.setText(_translate("MainWindow", "Privado"))
        self.CreatepushButton.setText(_translate("MainWindow", "Criar conta"))

